# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  force = true
  from = '/'
  status = 200
  to = '/.netlify/functions/index'

[[redirects]]
  force = true
  from = '/sheet/*'
  status = 200
  to = '/.netlify/functions/sheet/:splat'

[[redirects]]
  force = true
  from = '/update/*'
  status = 200
  to = '/.netlify/functions/update/:splat'

[[redirects]]
  force = true
  from = '/add/*'
  status = 200
  to = '/.netlify/functions/add/:splat'

[[redirects]]
  force = true
  from = '/delete/*'
  status = 200
  to = '/.netlify/functions/delete/:splat'

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/


[template.environment]
  GOOGLE_CLIENT_ID = "change me"
  GOOGLE_CLIENT_SECRET = "change me"
  ACCESS_TOKEN = "change me"
  REFRESH_TOKEN = "change me"
  REDIS_KEY = "change me"
  REDIS_HOST = "change me"

