name: Test

on:
  pull_request:
    branches: [main]

env:
  VOLTA_FEATURE_PNPM: 1


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:ci
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_KEY: ${{secrets.REDIS_KEY}}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
